# Generated by Django 5.2.5 on 2025-08-24 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAprobacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único de la solicitud', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título de la solicitud', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la solicitud')),
                ('solicitante', models.CharField(help_text='Usuario de red del solicitante', max_length=100)),
                ('responsable', models.CharField(help_text='Usuario de red del responsable de aprobar', max_length=100)),
                ('tipo_solicitud', models.CharField(choices=[('despliegue', 'Despliegue de Microservicio'), ('acceso', 'Acceso a Herramientas Internas'), ('cambio_tecnico', 'Cambio Técnico'), ('pipeline', 'Cambios en Pipeline/CI-CD'), ('incorporacion', 'Nueva Incorporación Técnica'), ('otro', 'Otro')], help_text='Tipo de solicitud', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual de la solicitud', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
            ],
            options={
                'verbose_name': 'Solicitud de Aprobación',
                'verbose_name_plural': 'Solicitudes de Aprobación',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='aprobacione_estado_0d9171_idx'), models.Index(fields=['tipo_solicitud'], name='aprobacione_tipo_so_b6b174_idx'), models.Index(fields=['solicitante'], name='aprobacione_solicit_3fd346_idx'), models.Index(fields=['responsable'], name='aprobacione_respons_cdb3a1_idx'), models.Index(fields=['fecha_creacion'], name='aprobacione_fecha_c_da430d_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Acción realizada (creada, aprobada, rechazada, etc.)', max_length=50)),
                ('usuario', models.CharField(help_text='Usuario que realizó la acción', max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la acción')),
                ('comentario', models.TextField(blank=True, help_text='Comentario o descripción de la acción')),
                ('estado_anterior', models.CharField(blank=True, help_text='Estado anterior antes del cambio', max_length=20)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='aprobaciones.solicitudaprobacion')),
            ],
            options={
                'verbose_name': 'Entrada de Historial',
                'verbose_name_plural': 'Entradas de Historial',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Usuario que hizo el comentario', max_length=100)),
                ('comentario', models.TextField(help_text='Contenido del comentario')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del comentario')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('aprobado', 'Aprobación'), ('rechazado', 'Rechazo'), ('revision', 'Revisión')], default='general', help_text='Tipo de comentario', max_length=20)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='aprobaciones.solicitudaprobacion')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
